[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Articles"
  pageRef = "/posts"
  weight = 20

[[main]]
  name = "About"
  pageRef = "/about"
  weight = 30

[[main]]
  name = "Projects"
  pageRef = "/projects"
  weight = 40
